name: Coreplank
options:
  bundleIdPrefix: com.shimondeitel.coreplank
  deploymentTarget:
    iOS: "17.0"
  createIntermediateGroups: true
  groupSortPosition: top
settings:
  base:
    MARKETING_VERSION: "1.0"
    CURRENT_PROJECT_VERSION: "1"
    SWIFT_VERSION: "5.0"
    DEVELOPMENT_TEAM: "W7Q885Q59C"
    CODE_SIGN_STYLE: Automatic
    IPHONEOS_DEPLOYMENT_TARGET: "17.0"
    TARGETED_DEVICE_FAMILY: "1"
    ENABLE_USER_SCRIPT_SANDBOXING: "YES"
targets:
  Coreplank:
    type: application
    platform: iOS
    sources:
      - path: Coreplank
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.coreplank
        TARGETED_DEVICE_FAMILY: "1"
        INFOPLIST_FILE: Coreplank/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        ENABLE_PREVIEWS: "YES"
        GENERATE_INFOPLIST_FILE: "NO"
  CoreplankTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: CoreplankTests
      - path: Coreplank.storekit
    dependencies:
      - target: Coreplank
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.coreplank.tests
        GENERATE_INFOPLIST_FILE: "YES"
        TARGETED_DEVICE_FAMILY: "1"
  CoreplankUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: CoreplankUITests
    dependencies:
      - target: Coreplank
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.coreplank.uitests
        GENERATE_INFOPLIST_FILE: "YES"
        TARGETED_DEVICE_FAMILY: "1"
schemes:
  Coreplank:
    build:
      targets:
        Coreplank: all
        CoreplankTests: [test]
        CoreplankUITests: [test]
    run:
      config: Debug
      storeKitConfiguration: Coreplank.storekit
    test:
      config: Debug
      storeKitConfiguration: Coreplank.storekit
      targets:
        - CoreplankTests
        - CoreplankUITests
    archive:
      config: Release
